# Generated by Django 2.1 on 2019-06-18 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='academy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy_name', models.CharField(max_length=20)),
                ('academy_area', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('classroom_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('size', models.IntegerField()),
                ('category', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['classroom_id'],
            },
        ),
        migrations.CreateModel(
            name='classroom_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_date', models.DateField()),
                ('apply_section_begin', models.IntegerField(default=0)),
                ('apply_section_end', models.IntegerField(default=0)),
                ('apply_reason', models.TextField()),
                ('apply_status', models.IntegerField(default=0)),
                ('apply_time', models.DateTimeField(auto_now_add=True)),
                ('pass_time_1', models.DateTimeField(null=True)),
                ('pass_time_2', models.DateTimeField(null=True)),
                ('refuse_reason', models.TextField(null=True)),
                ('apply_category', models.IntegerField(default=0)),
                ('apply_size', models.IntegerField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='classroom_apply_applicant', to=settings.AUTH_USER_MODEL)),
                ('apply_head_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='classroom_apply_apply_head_1', to=settings.AUTH_USER_MODEL)),
                ('apply_head_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='classroom_apply_apply_head_2', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='classroom_apply_classroom', to='application.classroom')),
                ('responsible_teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='classroom_apply_responsible_teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['apply_time'],
            },
        ),
        migrations.CreateModel(
            name='classroom_apply_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_date', models.DateField()),
                ('apply_section_begin', models.IntegerField(default=0)),
                ('apply_section_end', models.IntegerField(default=0)),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='classroom_apply_record_apply', to='application.classroom_apply')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='classroom_apply_record_classroom', to='application.classroom')),
            ],
            options={
                'ordering': ['use_date'],
            },
        ),
        migrations.CreateModel(
            name='curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('section_begin', models.IntegerField()),
                ('section_end', models.IntegerField()),
                ('week_day', models.IntegerField()),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='curriculum_academy', to='application.academy')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='curriculum_classroom', to='application.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('last_check_time', models.DateTimeField(auto_now_add=True)),
                ('device_type', models.IntegerField()),
                ('device_name', models.CharField(max_length=20)),
                ('storage_location', models.CharField(max_length=20)),
                ('is_stable', models.BooleanField(default=False)),
                ('responsible_staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='device_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.IntegerField()),
                ('device_name', models.CharField(max_length=20)),
                ('use_date', models.DateField()),
                ('apply_quatity', models.IntegerField()),
                ('apply_section_begin', models.IntegerField()),
                ('apply_section_end', models.IntegerField()),
                ('apply_reason', models.TextField()),
                ('apply_status', models.IntegerField(default=0)),
                ('apply_time', models.DateTimeField(auto_now_add=True)),
                ('pass_time', models.DateTimeField(null=True)),
                ('refuse_reason', models.TextField(null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='device_apply_to_user', to=settings.AUTH_USER_MODEL)),
                ('apply_head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='device_apply_apply_head', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='device_apply_classroom', to='application.classroom')),
                ('responsible_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='device_apply_responsible_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['apply_time'],
            },
        ),
        migrations.CreateModel(
            name='device_apply_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_date', models.DateField()),
                ('section_begin', models.IntegerField()),
                ('section_end', models.IntegerField()),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='device_apply_record_apply', to='application.device_apply')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='device_apply_record_device', to='application.device')),
            ],
            options={
                'ordering': ['use_date'],
            },
        ),
        migrations.CreateModel(
            name='device_broken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateField(auto_now_add=True)),
                ('detail', models.TextField(null=True)),
                ('status', models.BooleanField(default=0)),
                ('pass_time', models.DateField(null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='device_broken_applicant', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='device_broken_device', to='application.device')),
                ('pass_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='device_broken_pass_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['submit_time'],
            },
        ),
        migrations.CreateModel(
            name='major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=20)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.academy')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_admin', models.BooleanField(default=False)),
                ('staff_name', models.CharField(max_length=20)),
                ('classroom_admin', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_academy', to='application.academy')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_major', to='application.major')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.academy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['create_time'],
            },
        ),
    ]
