# Generated by Django 2.2 on 2019-06-18 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom_apply',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_apply_classroom', to='application.classroom'),
        ),
        migrations.AlterField(
            model_name='classroom_apply_record',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_apply_record_classroom', to='application.classroom'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_classroom', to='application.classroom'),
        ),
        migrations.AlterField(
            model_name='device_apply',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_apply_classroom', to='application.classroom'),
        ),
    ]
