# Generated by Django 2.2 on 2019-06-19 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20190618_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom_apply',
            name='responsible_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='classroom_apply_responsible_teacher', to='application.teacher'),
        ),
    ]
