# Generated by Django 2.2 on 2019-06-19 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20190619_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_broken',
            name='pass_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='device_broken_pass_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
